### ISSUE TITLE
Wrong argument order when calling WikiExtractor.py in fetch_corpus.sh

### ISSUE THREAD

**Issue by Lasmali** [alexandrainst/danlp#1]
"25M" needs to be in front of -b which specifies size of output files, instead of -q which suppresses reporting progress info.

**Comment by AmaliePauli** [comment]
Thanks, It is corrected now.

**Comment by Alkarex** [comment]
https://github.com/alexandrainst/danlp/commit/ccd807f9ebc7722d9c6549ec5d166dab3f87829a
