### ISSUE TITLE
BertTone always throws "UserWarning: Maximum length.."

### ISSUE THREAD

**Issue by nielsdh** [alexandrainst/danlp#112]
Hi, 

I just started using BertTone, and found an error, which causes BertTone to always throw the maximum length warning. Fx. after calling the encode_plus in BertTone._get_pred the warning is thrown if the dictionary input1 contains the key "overflowing_tokens", but this key seems to always be present, but the associated value is an empty list if there is no overflow.

A possible solution could be:

```Python
def _get_pred(self, tokenizer, model, max_lenght, sentence):
        input1 = tokenizer.encode_plus(sentence, add_special_tokens=True, return_tensors='pt',
                                                max_length=max_lenght, truncation=True, return_overflowing_tokens=True)
        if len(input1.get('overflowing_tokens', [])) > 0:
            warnings.warn('Maximum length for sequence exceeded, truncation may result in unexpected results. Consider running the model on a shorter sequenze then {} tokens'.format(max_lenght))
        pred = model(input1['input_ids'], token_type_ids=input1['token_type_ids'])[0]

        return pred
```

BR
Niels

**Comment by ophelielacroix** [comment]
Hi Niels, 

thanks for reporting the issue. 
Could you add some code for reproducing the error? 

BR, 
Ophélie

**Comment by nielsdh** [comment]
Hi Ophélie,

when I run this code:

```Python
from danlp.models import load_bert_tone_model
clf = load_bert_tone_model()
clf.predict('test')
```

I get this error: 

`bert_models.py:303: UserWarning: Maximum length for sequence exceeded, truncation may result in unexpected results. Consider running the model on a shorter sequenze then 512 tokens`


If I look at line 303 in bert_models, I can see that the warning is raised thrown when "overflowing_tokens" is in the variable input1, the value of input1 in this specific case is equal to:

```python
clf.tokenizer_sub.encode_plus("test", add_special_tokens=True, return_tensors='pt',
                                                max_length=512, truncation=True, return_overflowing_tokens=True)
```

and the output is:

`{'overflowing_tokens': tensor([], size=(1, 0)), 'num_truncated_tokens': tensor([-509]), 'input_ids': tensor([[   2, 1972,    3]]), 'token_type_ids': tensor([[0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1]])}`

Which seems to indicate that "overflowing_tokens" is always present, also when there is no overflow :-) 

Does this help?

Best 
Niels

**Comment by ophelielacroix** [comment]
Hi Niels,
thanks for the example! 
I couldn't reproduce the error because we are using transformers v3.1.0 in the danlp package, and in that case the output does not contain the "overflowing_tokens" parameter. Apparently it happens when using transformers>=3.2.0.
That's good to know!
