### ISSUE TITLE
Error in model output

### ISSUE THREAD

**Issue by KennethEnevoldsen** [alexandrainst/danlp#122]
In your model description you provide these model outputs:
```
from danlp.models import load_bert_emotion_model
classifier = load_bert_emotion_model()

# using the classifier
classifier.predict('bilen er flot')
''''No emotion''''
classifier.predict('jeg ejer en rød bil og det er en god bil')
''''Tillid/Accept''''
classifier.predict('jeg ejer en rød bil men den er gået i stykker')
''''Sorg/trist''''
```

While I get these model outputs:
```
from danlp.models import load_bert_emotion_model
classifier = load_bert_emotion_model()

# using the classifier
print(classifier.predict('bilen er flot'))
print(classifier.predict('jeg ejer en rød bil og det er en god bil'))
print(classifier.predict('jeg ejer en rød bil men den er gået i stykker'))
```

```
Tillid/Accept
Tillid/Accept
Sorg/trist
```

The DaNLP version used is: '0.0.11' (tried both the pipy version and GitHub version). 

More generally it seems like I have had a hard time making the model detecting "No emotion" at all.

**Comment by ophelielacroix** [comment]
Hello, 
it seems that it is an error in the documentation. The output of `print(classifier.predict('bilen er flot'))` is `Tillid/Accept` as you mention. 
The two other examples are correct. 
An example of a `No emotion` prediction would be for : `classifier.predict('Der er et træ i haven')`.

**Comment by KennethEnevoldsen** [comment]
Thanks for the Clarification Ophelia. I will close this issue then.
