### ISSUE TITLE
Coreference model

### ISSUE THREAD

**Issue by linguist89** [alexandrainst/danlp#123]
The README states instructions for using the XLMR coreference model, but I don't think the model is updated in the repo because with the stated imports it still throws an error that the model doesn't exist.

**Comment by ophelielacroix** [comment]
Hello, 
the coreference model is not part of the last version of the package yet. 
Soon we should release a new version including it. 
You can install the latest changes through: `pip install git+https://github.com/alexandrainst/danlp.git`. 
Let me know if it still doesn't work after installing it. 
Note that there might be some compatibility issues between the packages when installing the dependencies using the requirements file. But installing transformers==3.5.1 and allennlp==1.3.0 independently should work.
