### ISSUE TITLE
SSL Certificate for Danlp Downloads site expired

### ISSUE THREAD

**Issue by smaakage85** [alexandrainst/danlp#131]
Related to issue #12.

The SSL certificate for your danlp downloads has expired (making it hard to access your uploaded datasets/models).

![image](https://user-images.githubusercontent.com/24368532/119646777-d44cd200-be1f-11eb-8483-fc8137fe7ae4.png)

**Comment by ophelielacroix** [comment]
Thanks for the notice. 
It is because we have moved the models and datasets to another server. 
We are working on the issue!
