### ISSUE TITLE
Compatibility with Gensim 4.0.0?

### ISSUE THREAD

**Issue by Bonnevie** [alexandrainst/danlp#140]
Gensim has been updated to a new major version (4.0.0), but DaNLP is tied to an older version of Gensim (3.8); is it possible to update to a later version or do you expect it to be incompatible in some manner?
Tried updating with `pip` and running `load_wv_with_gensim` (using the test code) and this seemed to work with 4.0.0. Any reason to suspect 4.0.0 isn't properly supported?

**Comment by ophelielacroix** [comment]
Thanks for notifying us about the new version. 
Currently, we cannot upgrade Gensim to 4.0.0 because it is a dependency for flair which only allows versions up to 3.8.3.
