### ISSUE TITLE
outdated SSL certificate in the downloads url (https://danlp-downloads.alexandra.dk/)

### ISSUE THREAD

**Issue by AsbjornLind** [alexandrainst/danlp#153]
**Describe the bug**
SSL certificate is outdated, so the site looks like an unsecure website. Hence the model can't be loaded without turning off ssl verification. 
I wanted to use this project in google cloud, but i get this error when running it on a cloud function; 

urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)>

On my phone (4g network) i can see that the license expired 8 days ago if thats any help. 

**To Reproduce**
open; https://danlp-downloads.alexandra.dk/

**Your Environment**
 - Operating system: windows 10
 - Python version: python 3,9
 - DaNLP version: 0.1.1

**Comment by AsbjornLind** [comment]
update: 
This is the code snippet I run:


```
from danlp.models import load_bert_tone_model

classifier = load_bert_tone_model()

def get_sentiment(tweets):
    analytic = []
    sentiment = []    
    for sentence in tweets:
        sentiment.append(classifier.predict(sentence)['polarity'])
        analytic.append(classifier.predict(sentence)['analytic'])
    return sentiment, analytic 
```

**Comment by ophelielacroix** [comment]
Thanks for notifying us about the problem. 
It is fixed now so you should be able to download the models.
