### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/mupvsvpuzotw.tmp'

### ISSUE THREAD

**Issue by jolsso** [alexandrainst/danlp#18]
When doing 
```python
from danlp.datasets import DDT
ddt = DDT()

nlp = ddt.load_with_spacy()
```
I get the following error:
```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-8-04e2151cfe39> in <module>
      7 
      8 from danlp.datasets import DDT
----> 9 ddt = DDT()
     10 
     11 nlp = ddt.load_with_spacy()

~\Anaconda3\envs\spacy\lib\site-packages\danlp\datasets\ddt.py in __init__(self, cache_dir)
     22         self.dataset_name = 'ddt'
     23         self.file_extension = DATASETS[self.dataset_name]['file_extension']
---> 24         self.dataset_dir = download_dataset('ddt', process_func=_unzip_process_func, cache_dir=cache_dir)
     25 
     26     def load_as_conllu(self, predefined_splits: bool = False):

~\Anaconda3\envs\spacy\lib\site-packages\danlp\download.py in download_dataset(dataset, cache_dir, process_func, verbose)
    146         file_path = os.path.join(cache_dir, dataset)
    147 
--> 148         _download_and_process(dataset_info, process_func, file_path, verbose)
    149 
    150     else:

~\Anaconda3\envs\spacy\lib\site-packages\danlp\download.py in _download_and_process(meta_info, process_func, single_file_path, verbose)
    226         tmp_file_path = "/tmp/{}.tmp".format(random_string())
    227 
--> 228         _download_file(meta_info, tmp_file_path, verbose=verbose)
    229 
    230         process_func(tmp_file_path, meta_info, verbose=verbose, clean_up_raw_data=True)

~\Anaconda3\envs\spacy\lib\site-packages\danlp\download.py in _download_file(meta_info, destination, verbose)
    255         else:
    256             print("Downloading file {}".format(destination))
--> 257             urllib.request.urlretrieve(url, destination)
    258 
    259     else:

~\Anaconda3\envs\spacy\lib\urllib\request.py in urlretrieve(url, filename, reporthook, data)
    256         # Handle temporary file setup.
    257         if filename:
--> 258             tfp = open(filename, 'wb')
    259         else:
    260             tfp = tempfile.NamedTemporaryFile(delete=False)

FileNotFoundError: [Errno 2] No such file or directory: '/tmp/mupvsvpuzotw.tmp'
```
Can you switch to using https://docs.python.org/3/library/tempfile.html or similar to make downloading cross platform?

Keep up the good work! (y)

**Comment by hvingelby** [comment]
Hi @jolsso, thank you for reporting this issue!

I can see you are running anaconda, but on what OS? :)

**Comment by jolsso** [comment]
Hi!
On Windows 10. I'll post exact build number etc when I get near the PC again. I made the changes to the code, which made it possible to download and run (mainly encoding stuff + is lookups). I can do a PR of you'd like the changes?

**Comment by hvingelby** [comment]
That sounds very nice! You are more than welcome to do a PR. 

I use Linux myself so i can verify that it works :+1:

**Comment by MalteHB** [comment]
First of all: Love the work of you guys! Danish NLP rocks!

This is, however, still an issue. Will it be fixed anytime soon? 

@jolsso i see you found a solution - did you share it somewhere?

**Comment by parsa-mz** [comment]
when running ``` py autogen.py add_example vision/ ``` I got an error :

Traceback (most recent call last):
  File "autogen.py", line 903, in <module>
    keras_io.add_example(
  File "autogen.py", line 232, in add_example
    tutobooks.py_to_md(py_path, nb_path, md_path, img_dir, working_dir=working_dir)
  File "C:\Users\Primz\desktop\keras-io\scripts\tutobooks.py", line 259, in py_to_md
    nb_to_md(nb_path, md_path, img_dir, working_dir=working_dir)
  File "C:\Users\Primz\desktop\keras-io\scripts\tutobooks.py", line 220, in nb_to_md
    shutil.copyfile(nb_path, nb_fname)
  File "C:\Users\Primz\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 241, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
what should I do ?

**Comment by hvingelby** [comment]
Hi @parsa-mz,

I am not sure what you are trying to achieve?
