### ISSUE TITLE
named entity consistency

### ISSUE THREAD

**Issue by KennethEnevoldsen** [alexandrainst/danlp#24]
First of all great work!

Is there a way to see if two entities are the same? E.g. in the sentence:

"Charlie gik en tur med sin hund som hund Chili. På vejen mødte Charlie sin gamle ven Peter"

Charlie and Charlie would be the same entity. Currently the flair .get_spans('ner') does not solve this. Are we missing something?

Minor issues we have noted so far which you might find interesting:
1) it seems to overfit to uppercase letters, which becomes especially transparent when using internet data where the casing of the letter is less important (this is probably due to the training set, I wonder if training it on a all lowercased + uppercased as a form of data augmentation would improve performance)
2) It seems that punctuation is a part of the entity (e.g. "Chili." in the above sentence), I understand that this is probably a part flair framework

**Comment by hvingelby** [comment]
Hi Kenneth, thanks for creating this issue. Recognizing whether two entities are the same entity is a part of the harder task coreference resolution. As far as I know this is unfortunately not supported by any models in Danish yet.

Thank you for pointing out some of the issues with the model. We are aware that the model can still be improved especially in terms of robustness as you are mentioning :slightly_smiling_face:

**Comment by KennethEnevoldsen** [comment]
Thanks for the answer, we were suspecting as much. I will close the issue
