### ISSUE TITLE
Pip install does not fully work

### ISSUE THREAD

**Issue by Glagnar** [alexandrainst/danlp#3]
The examples in the jupiter notebook require e.g. polyglot. Please document how to do this, and what is needed.
( I am not an expert, but the process was quite involved in MacOS Mojave and took a lot of tweaking )

**Comment by AmaliePauli** [comment]
The README file and the jupyter notebook with the part of speech tag example is now update to make the installation guide  more clear. 
The DaNLP package is not installing all the packages - this is to keep the installation smaller and make it a free choice which packages to use. 
A Docker Image is added that should setup all the dependencies as well as the jupyter notebook - this is to make it easier to start. 
I hope this make it clearer, else please leave a comment.
 
8f3539e819b75e3a90321c31e9d5d824edd473ca
