### ISSUE TITLE
Datasets-folder misses the sentida.py file

### ISSUE THREAD

**Issue by mbondehansen** [alexandrainst/danlp#33]
When you pip install danlp and want to look at the benchmark of the sentiment analyses, you don't get the sentida.py inside the danlp/datasets-folder. 

Fix: download the sentida.py and place it in the folder and in the __init__.py you add "from .sentiment import *".

Another issue I run into is that the sentiment datasets aren't included in the download.py file. How can you fix this?

**Comment by AmaliePauli** [comment]
Hi,
The pip package is not up to date with the github and therefor the pip package do not include the sentiment becnhmark script. Clone instead the github and install directly in the folder by running  "pip install .". Hope this help.
