### ISSUE TITLE
Add DaNLP to repository for pip install ?

### ISSUE THREAD

**Issue by Glagnar** [alexandrainst/danlp#4]
Is it possible to install without having to download the source ? E.g.
```
pip install danlp==0.4.5
```

**Comment by hvingelby** [comment]
Yes this is possible, and we will look into this this week.

**Comment by hvingelby** [comment]
You can now find DaNLP on PyPI, and install it directly with `pip install danlp`

This is fixed with https://github.com/alexandrainst/danlp/commit/67c3ff3a168e25f818e45837e4bba38e8cc91be6.
