### ISSUE TITLE
IndexError when using BertTone with sequences longer than 512 tokens

### ISSUE THREAD

**Issue by lewisbails** [alexandrainst/danlp#54]
NB: This may apply to other BERT models, but my experience is only with BertTone.

The pre-trained BertTone model has 512 position embeddings. If the tokenizer produces a tokenized document longer than this we get a IndexError when the model looks for the 512th positional embedding.

I propose setting a max_length parameter when calling encode_plus with the tokenizer attribute, and warning the user of the overflow.

```python

class BertTone:
...
    
def __init__(self, cache_dir=DEFAULT_CACHE_DIR, verbose=False):
...
    self.max_length_sub = self.model_sub.bert.embeddings.position_embeddings.num_embeddings
    self.max_length_pol = self.model_pol.bert.embeddings.position_embeddings.num_embeddings

def predict_proba(self, sentence: str, polarity: bool = True, analytic: bool = True):
    proba=[]
    sentence = self._clean(str(sentence))
        
    # predict polarity
    if polarity:
        input1 = self.tokenizer_pol.encode_plus(sentence, add_special_tokens=True, return_tensors='pt', max_length=self.max_length_pol, return_overflowing_tokens=True)
        if len(input1['overflowing_tokens']):
            warnings.warn('Maximum length for sequence exceeded, truncation may result in unexpected results', MaxLengthExceededWarning)
        pred = (self.model_pol(input1['input_ids'], token_type_ids=input1['token_type_ids'])[0])
        proba.append(torch.nn.functional.softmax(pred[0], dim=0).detach().numpy())
```

**Comment by AmaliePauli** [comment]
Hi lewisbails, 
Thanks for the issue and for your solution. 
It is with 5cc0532f86c312b9973ac7f0e1c3c71f9c62a66f possible to use both bertTone and bertEmotion when the tokenizer embed longer the 512, however, in general it is not recommended and I put a warning as you suggested. For bertNER I do not think it makes sense to allow longer tokenizied sequences, so that on is unchanged.

Amalie
