### ISSUE TITLE
DaNE no longer accessible

### ISSUE THREAD

**Issue by alanakbik** [alexandrainst/danlp#55]
Hello all, thanks for the great datasets. We noticed over in Flair (https://github.com/flairNLP/flair/issues/1782) that DDT.zip at the given download link https://danlp.s3.eu-central-1.amazonaws.com/datasets/ddt.zip is no longer reachable. Can you check?

**Comment by AmaliePauli** [comment]
Hi Alanakbik, 
We had to move all our files to locale storage, it can now be found at:
https://danlp.alexandra.dk/304bd159d5de/datasets/ddt.zip
I am sorry for the inconvenience!
Amalie

**Comment by maziyarpanahi** [comment]
Thanks @alanakbik and @AmaliePauli 

I made PR to fix this in Flair: https://github.com/flairNLP/flair/pull/1800
