### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for BertForSequenceClassification

### ISSUE THREAD

**Issue by Lunde89** [alexandrainst/danlp#57]
Full error message: 
Error(s) in loading state_dict for BertForSequenceClassification:
	size mismatch for classifier.weight: copying a param with shape torch.Size([3, 768]) from checkpoint, the shape in current model is torch.Size([2, 768]).
	size mismatch for classifier.bias: copying a param with shape torch.Size([3]) from checkpoint, the shape in current model is torch.Size([2]).

Trying to run the following code:
`from danlp.models import load_bert_tone_model`
`classifier = load_bert_tone_model()`

Using:
Torch 1.6+cpu
Python 3.7.4
daNLP 0.0.4

**Comment by AmaliePauli** [comment]
Hi Lunde89, 
The DaNLP version 0.0.4 do not support the BertTone model, please update the package to version 0.0.9 .
I hope this will fix your issue.
Amalie

**Comment by Lunde89** [comment]
Hi Amalie, 

I might have mis-typed in the original comment. Sorry about that. At least, i'm using 0.0.9 now - and it produces the same error.

**Comment by AmaliePauli** [comment]
Alright, what about the transformes version? You also need this package for it to run. It is tested with transformers==2.3.0. ?

**Comment by Lunde89** [comment]
Hi Amalie, 

I figured out the issue The problem is that the version you get from PyPi isn't the same as the one on this repository. After i installed from source, everything works like a charm! 👍

**Comment by KennethEnevoldsen** [comment]
Just to +1 this comment I have had the exact same problem. Seems like an update of the PyPi is needed.

**Comment by kirajen** [comment]
Hi all,

I am now facing the same issue. I have ensured all my versions are as in the comment above.

**Comment by KennethEnevoldsen** [comment]
So @kirajen please try updating to the latest version:
```
pip install git+https://github.com/alexandrainst/danlp.git
```
