### ISSUE TITLE
Pre-trained BERT model 

### ISSUE THREAD

**Issue by JensMadsen** [alexandrainst/danlp#58]
Ohøj

Two questions:

- [ ] Do you still use the weights for BERT provided by XOBot or have you progressed any further? If so I can provide 100000 danish juridical documents for further pretraining if you are interested
- [ ] Is it possible to download the pretrained BERT model that you use before pre-training (or do you pretrin the model provided by XoBot)?

**Comment by AmaliePauli** [comment]
Hej Jens,

We use the pretrained model open sourced by botxo, and it can be download here: https://github.com/botxo/nordic_bert

And lets keep the dialog through mails.:) 

Amalie
