### ISSUE TITLE
[Improvements] Add runtime efficiency

### ISSUE THREAD

**Issue by KennethEnevoldsen** [alexandrainst/danlp#84]
The performance metrics presented are great and good for comparing models, I myself have already used them a bit. Notably lacking are Stanza and UDpipe, which both have Danish specific models. (stanza added as pull request)

 However, the methods vary greatly at inference time and whether it was run on a GPU or not. I recommend that you add two tabs.
- 1) Runtime efficiency CPU 
- 2) Runtime efficiency GPU

(naturally, these would need to be limited to be the same every time)

To allow the user to make meaningful comparisons between models as currently simple and efficient models such as polyglot is compared to deep neural models such as bi-LSTMs and Transformer architectures, which in general perform better, but at a higher compute cost.

Once again great resource,
Kenneth, Center for Humanities Computing Aarhus

**Comment by AmaliePauli** [comment]
Thanks! Yes I agree, it is also on our project board - @ophelielacroix  did you start looking at this already?
